image: node:latest

stages:
  - test
  - staging

test:
  image: node:latest
  stage: test
  script:
    - npm install
    - npm run test
  only:
    - deploy
  tags:
    - docker

staging:
  stage: staging
  environment:
    name: staging
    url: https://subs-it.herokuapp.com/
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=subs-it --api-key=80e04161-5631-43d0-9b6b-4ee0ef01f6c7
  only:
    - deploy
  tags:
    - docker
